server:
    verbosity: 1
    interface: 0.0.0.0@5335
    access-control: 127.0.0.0/8 allow
    access-control: 192.168.0.0/16 allow
    access-control: 172.16.0.0/12 allow
    access-control: 10.0.0.0/8 allow
    access-control: 0.0.0.0/0 refuse
    num-threads: 2
    msg-cache-size: 64m
    rrset-cache-size: 128m
    cache-min-ttl: 300
    cache-max-ttl: 86400
    prefetch: yes
    prefetch-key: yes
    root-hints: "/opt/unbound/etc/root.hints"
    auto-trust-anchor-file: "/opt/unbound/etc/root.key"
    val-clean-additional: yes
    val-permissive-mode: no
    qname-minimisation: yes
    qname-minimisation-strict: yes
    pad-responses: yes
    hide-identity: yes
    hide-version: yes
    outgoing-range: 8192
    num-queries-per-thread: 4096
    edns-buffer-size: 1232
    max-udp-size: 1232
    unwanted-reply-threshold: 10000
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes
    harden-algo-downgrade: yes
    harden-short-bufsize: yes
    harden-large-queries: yes
    harden-below-nxdomain: yes
    harden-referral-path: yes
    use-caps-for-id: yes

forward-zone:
    name: "."
    forward-tls-upstream: yes
    forward-addr: 1.1.1.1@853#cloudflare-dns.com
    forward-addr: 1.0.0.1@853#cloudflare-dns.com
    forward-addr: 9.9.9.9@853#dns.quad9.net
    forward-addr: 149.112.112.112@853#dns.quad9.net
