---
ansible_user: "{{ vault_ansible_user | default('your_username') }}"
ssh_public_key: "{{ vault_ssh_public_key | default('ssh-rsa AAAA...') }}"
domain_name: "{{ vault_domain_name | default('homelab.lan') }}"

zfs_disk1: "{{ vault_zfs_disk1 | default('') }}"
zfs_disk2: "{{ vault_zfs_disk2 | default('') }}"
ts_auth_key: "{{ vault_ts_auth_key | default('') }}"
