extends: default

rules:
  line-length:
    max: 200
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  brackets:
    max-spaces-inside: 1
  indentation:
    spaces: 2
    indent-sequences: consistent
  document-start: disable
  truthy:
    level: warning
