---
all:
  hosts:
    homelab-server:
      ansible_host: 127.0.0.1
      ansible_connection: local

  children:
    ai_hosts:
      hosts:
        homelab-server:
    vm_hosts:
      hosts:
        homelab-server:
    casaos_hosts:
      hosts:
        homelab-server:
