services:
  teamspeak:
    image: teamspeak:latest
    container_name: teamspeak
    restart: unless-stopped
    ports:
      - "9987:9987/udp"
      - "10011:10011"
      - "30033:30033"
    volumes:
      - teamspeak_data:/var/ts3server
    environment:
      - TS3SERVER_LICENSE=accept
    networks:
      - homelab

volumes:
  teamspeak_data:

networks:
  homelab:
    external: true
