---
# TeamSpeak – Voice-Server

x-common: &common
  restart: unless-stopped
  security_opt: ["no-new-privileges:true"]
  cap_drop: [ALL]
  networks: [backend]

services:
  teamspeak:
    <<: *common
    image: teamspeak/teamspeak:3.13.7
    container_name: teamspeak
    ports:
      - "9987:9987/udp"
      - "10011:10011"
      - "30033:30033"
    volumes:
      - teamspeak_data:/var/ts3server
    environment:
      - TS3SERVER_LICENSE=accept
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "10011"]
      interval: 60s
      timeout: 5s
      retries: 5

volumes:
  teamspeak_data:

networks:
  backend:
    external: true
